[workspace]
members = ["workspace/apps/staking/contracts"]

[workspace.dependencies]
starknet = "2.11.0"
assert_macros = "2.11.0"
openzeppelin = "1.0.0"
openzeppelin_testing = "1.0.0"
snforge_std = "0.38.3"
starkware_utils = { git = "https://github.com/starkware-libs/starkware-starknet-utils", tag = "v0.1.1" }
starkware_utils_testing = { git = "https://github.com/starkware-libs/starkware-starknet-utils", tag = "v0.1.1" }

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[[workspace.tool.snforge.fork]]
name = "MAINNET_LATEST"

url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"

block_id.tag = "latest"
